name: Install and Validate Packer

on:
  pull_request:
    branches:
      - main

jobs:
  packer-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven -y

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Use gcloud CLI
        run: 'gcloud info'

      - name: Build Application with Maven and Run Integration Test
        run: |
          echo "LOG_FILE_PATH:  ${{ secrets.LOG_FILE_PATH }}" >> .env
          mvn clean install
          pwd
          mkdir cloud && cp target/csye6225-0.0.1-SNAPSHOT.jar cloud   
          cp cloud/*.jar packer
          cd packer && ls -al
        env:
          MYSQL_DB_USERNAME: ${{ secrets.MYSQL_DB_USERNAME }}
          MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
          MYSQL_DB_DATABASE: ${{ secrets.MYSQL_DB_DATABASE }}
          MYSQL_DB_HOST: ${{ secrets.MYSQL_DB_HOST }}
          MYSQL_DB_PORT: ${{ secrets.MYSQL_DB_PORT }}
          GCP_PUBSUB_TOPIC_NAME: ${{ secrets.GCP_PUBSUB_TOPIC_NAME }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Create .env file
        run: |
          echo "MYSQL_DB_USERNAME=${{ secrets.MYSQL_DB_USERNAME }}" >> .env
          echo "MYSQL_DB_PASSWORD=${{ secrets.MYSQL_DB_PASSWORD }}" >> .env
          echo "MYSQL_DB_DATABASE=${{ secrets.MYSQL_DB_DATABASE }}" >> .env
          echo "MYSQL_DB_HOST=${{ secrets.MYSQL_DB_HOST }}" >> .env
          echo "MYSQL_DB_PORT=${{ secrets.MYSQL_DB_PORT }}" >> .env
          echo "LOG_FILE_PATH=${{ secrets.LOG_FILE_PATH }}" >> .env
          echo "GCP_PUBSUB_TOPIC_NAME=${{ secrets.GCP_PUBSUB_TOPIC_NAME }}" >> .env
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> .env
          cat .env
          cp .env packer
          cd packer && ls -al

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Initialize Packer
        run: |
          cd packer
          packer init .

      - name: Format check Packer
        run: |
          cd packer
          CHANGES=$(git diff --name-only)
          packer fmt -check .
          if [ $? -ne 0 ]; then
            echo "Packer template was modified by 'packer fmt' command."
            echo "$CHANGES"
            exit 1
          fi

      - name: Validate Packer
        run: |
          cd packer
          packer validate .
          if [ $? -ne 0 ]; then
            echo "Packer template validation failed."
            exit 1
          fi
        env:
          PKR_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          PKR_VAR_gcp_zone: ${{ secrets.GCP_ZONE }}
          PKR_VAR_ssh_username : ${{ secrets.PACKER_SSH_USERNAME }}
          PKR_VAR_source_image_family: ${{ secrets.SOURCE_IMAGE_FAMILY }}
          PKR_VAR_network: ${{ secrets.NETWORK }}
          PKR_VAR_image_storage_locations: ${{ secrets.IMAGE_STORAGE_LOCATIONS }}
          PKR_VAR_image_name: ${{ secrets.IMAGE_NAME }}
          PKR_VAR_image_family: ${{ secrets.IMAGE_FAMILY }}
          PKR_VAR_image_description : ${{ secrets.IMAGE_DESCRIPTION }}
          PKR_VAR_build_name : ${{ secrets.BUILD_NAME }}

